CREATE TABLE IF NOT EXISTS CAMINHO(
ID INT PRIMARY KEY auto_increment,
CAMINHO INT
);
SET SQL_SAFE_UPDATES=0;
UPDATE CAMINHO SET CAMINHO=1 WHERE ID=1;
INSERT INTO CAMINHO(CAMINHO)VALUES(1);
DELIMITER //
CREATE PROCEDURE adicionar()
BEGIN
UPDATE CAMINHO SET CAMINHO=CAMINHO+1 WHERE ID=1;
END//
call adicionar();
delimiter //
create procedure diminuir()
begin
UPDATE CAMINHO SET CAMINHO=CAMINHO-1 WHERE ID=1;
end//

call diminuir();
select * from caminho;

